### rol gerente
GET http://127.0.0.1:8000/api/v1/usuario
Accept: application/json
Authorization: Bearer 40|s5M9m3BIMfsGU23KqE7d6sTnCvg6a9ZrOI11rgPQ

### rol user
GET http://127.0.0.1:8000/api/v1/usuario
Accept: application/json
Authorization: Bearer 41|RkoqtK8TrnXnOxw7zJ2bfy7r6M0tbFAlxeWWHYcd


### rol user
GET http://127.0.0.1:8000/api/v1/usuario
Accept: application/json
Authorization: Bearer 47|JKmDeyfqTgrrYSVlm1b56RmJv8xF18kx8GC7SnBg



### Guardar usuario
POST http://127.0.0.1:8000/api/v1/usuario
Accept: application/json
Content-Type: application/json
Authorization: Bearer 41|RkoqtK8TrnXnOxw7zJ2bfy7r6M0tbFAlxeWWHYcd

{
    "name": "prueba3",
    "email": "prueba3@mail.com",
    "password": "prueba54321"
}

